version: "3.8"
services:
  backendservice:
    container_name: backend-financial-monitoring
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/hakaton_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backendservice:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - financial-network
    depends_on:
      - postgres

  uiservice:
    container_name: ui-financial-monitoring
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - financial-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: "hakaton_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - hakaton_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d hakaton_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    networks:
      - financial-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.3
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.me"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - financial-network
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - './config/prometheus/:/etc/prometheus/'
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - financial-network
    depends_on:
      - backendservice

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana/datasources/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml"
      - "./config/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./config/grafana/prometheus:/var/lib/grafana/dashboards/prometheus"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 -O- http://grafana:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - financial-network
    depends_on:
      - backendservice
      - prometheus

volumes:
  hakaton_db-data:
  pgadmin-data:

networks:
  financial-network:
    driver: bridge
