{
 "title": "Метрики сервиса",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Транзакции",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transactions_NEW{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Новые"
    },
    {
     "expr": "transactions_CONFIRMED{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Подтвержденные"
    },
    {
     "expr": "transactions_IN_PROGRESS{job=\"backend-financial-monitoring\"}",
     "legendFormat": "В обработке"
    },
    {
     "expr": "transactions_ABORTED{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Отмененные"
    },
    { "expr": "transactions_SUCCESS", "legendFormat": "Оплаченные" },
    {
     "expr": "transactions_DELETED{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Удаленные"
    },
    {
     "expr": "transactions_RETURN{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Возвраты"
    }
   ]
  },
  {
   "title": "Пользователи",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_all{job=\"backend-financial-monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Категории",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "categories_all{job=\"backend-financial-monitoring\"}",
     "legendFormat": "Все категории"
    }
   ]
  }
 ]
}